(cl:defpackage nodes-msg
  (:use )
  (:export
   "<ENCODER>"
   "ENCODER"
   "<ROBOTANGLES>"
   "ROBOTANGLES"
   "<ACCGYRO>"
   "ACCGYRO"
   "<LEGPOSITION>"
   "LEGPOSITION"
   "<ROBOTFORCES>"
   "ROBOTFORCES"
   "<FORCE>"
   "FORCE"
   "<LEGCOMMAND>"
   "LEGCOMMAND"
   "<ROBOTINERTIAMEASUREMENTS>"
   "ROBOTINERTIAMEASUREMENTS"
   "<POSITION>"
   "POSITION"
   "<PWM>"
   "PWM"
   "<LEGENCODERS>"
   "LEGENCODERS"
  ))

