// Generated by gencpp from file nodes/AccGyro.msg
// DO NOT EDIT!


#ifndef NODES_MESSAGE_ACCGYRO_H
#define NODES_MESSAGE_ACCGYRO_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace nodes
{
template <class ContainerAllocator>
struct AccGyro_
{
  typedef AccGyro_<ContainerAllocator> Type;

  AccGyro_()
    : accX(0)
    , accY(0)
    , accZ(0)
    , gyroX(0)
    , gyroY(0)
    , gyroZ(0)
    , imu_dev(0)  {
    }
  AccGyro_(const ContainerAllocator& _alloc)
    : accX(0)
    , accY(0)
    , accZ(0)
    , gyroX(0)
    , gyroY(0)
    , gyroZ(0)
    , imu_dev(0)  {
    }



   typedef int16_t _accX_type;
  _accX_type accX;

   typedef int16_t _accY_type;
  _accY_type accY;

   typedef int16_t _accZ_type;
  _accZ_type accZ;

   typedef int16_t _gyroX_type;
  _gyroX_type gyroX;

   typedef int16_t _gyroY_type;
  _gyroY_type gyroY;

   typedef int16_t _gyroZ_type;
  _gyroZ_type gyroZ;

   typedef int8_t _imu_dev_type;
  _imu_dev_type imu_dev;




  typedef boost::shared_ptr< ::nodes::AccGyro_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::nodes::AccGyro_<ContainerAllocator> const> ConstPtr;

}; // struct AccGyro_

typedef ::nodes::AccGyro_<std::allocator<void> > AccGyro;

typedef boost::shared_ptr< ::nodes::AccGyro > AccGyroPtr;
typedef boost::shared_ptr< ::nodes::AccGyro const> AccGyroConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::nodes::AccGyro_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::nodes::AccGyro_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace nodes

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'nodes': ['/home/legged/tns_ros1/controllers/joystick/catkin_ws/src/nodes/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::nodes::AccGyro_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::nodes::AccGyro_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::nodes::AccGyro_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::nodes::AccGyro_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::nodes::AccGyro_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::nodes::AccGyro_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::nodes::AccGyro_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5d5d7c2c2052f4a1b0126c91ce7e3c6b";
  }

  static const char* value(const ::nodes::AccGyro_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5d5d7c2c2052f4a1ULL;
  static const uint64_t static_value2 = 0xb0126c91ce7e3c6bULL;
};

template<class ContainerAllocator>
struct DataType< ::nodes::AccGyro_<ContainerAllocator> >
{
  static const char* value()
  {
    return "nodes/AccGyro";
  }

  static const char* value(const ::nodes::AccGyro_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::nodes::AccGyro_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int16 accX\n\
int16 accY\n\
int16 accZ\n\
int16 gyroX\n\
int16 gyroY\n\
int16 gyroZ\n\
int8 imu_dev\n\
\n\
";
  }

  static const char* value(const ::nodes::AccGyro_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::nodes::AccGyro_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.accX);
      stream.next(m.accY);
      stream.next(m.accZ);
      stream.next(m.gyroX);
      stream.next(m.gyroY);
      stream.next(m.gyroZ);
      stream.next(m.imu_dev);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct AccGyro_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::nodes::AccGyro_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::nodes::AccGyro_<ContainerAllocator>& v)
  {
    s << indent << "accX: ";
    Printer<int16_t>::stream(s, indent + "  ", v.accX);
    s << indent << "accY: ";
    Printer<int16_t>::stream(s, indent + "  ", v.accY);
    s << indent << "accZ: ";
    Printer<int16_t>::stream(s, indent + "  ", v.accZ);
    s << indent << "gyroX: ";
    Printer<int16_t>::stream(s, indent + "  ", v.gyroX);
    s << indent << "gyroY: ";
    Printer<int16_t>::stream(s, indent + "  ", v.gyroY);
    s << indent << "gyroZ: ";
    Printer<int16_t>::stream(s, indent + "  ", v.gyroZ);
    s << indent << "imu_dev: ";
    Printer<int8_t>::stream(s, indent + "  ", v.imu_dev);
  }
};

} // namespace message_operations
} // namespace ros

#endif // NODES_MESSAGE_ACCGYRO_H
