// Generated by gencpp from file nodes/camera_get_info.msg
// DO NOT EDIT!


#ifndef NODES_MESSAGE_CAMERA_GET_INFO_H
#define NODES_MESSAGE_CAMERA_GET_INFO_H

#include <ros/service_traits.h>


#include <nodes/camera_get_infoRequest.h>
#include <nodes/camera_get_infoResponse.h>


namespace nodes
{

struct camera_get_info
{

typedef camera_get_infoRequest Request;
typedef camera_get_infoResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct camera_get_info
} // namespace nodes


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::nodes::camera_get_info > {
  static const char* value()
  {
    return "c2fc2a5a100c439ef9bdd511a6287c65";
  }

  static const char* value(const ::nodes::camera_get_info&) { return value(); }
};

template<>
struct DataType< ::nodes::camera_get_info > {
  static const char* value()
  {
    return "nodes/camera_get_info";
  }

  static const char* value(const ::nodes::camera_get_info&) { return value(); }
};


// service_traits::MD5Sum< ::nodes::camera_get_infoRequest> should match 
// service_traits::MD5Sum< ::nodes::camera_get_info > 
template<>
struct MD5Sum< ::nodes::camera_get_infoRequest>
{
  static const char* value()
  {
    return MD5Sum< ::nodes::camera_get_info >::value();
  }
  static const char* value(const ::nodes::camera_get_infoRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::nodes::camera_get_infoRequest> should match 
// service_traits::DataType< ::nodes::camera_get_info > 
template<>
struct DataType< ::nodes::camera_get_infoRequest>
{
  static const char* value()
  {
    return DataType< ::nodes::camera_get_info >::value();
  }
  static const char* value(const ::nodes::camera_get_infoRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::nodes::camera_get_infoResponse> should match 
// service_traits::MD5Sum< ::nodes::camera_get_info > 
template<>
struct MD5Sum< ::nodes::camera_get_infoResponse>
{
  static const char* value()
  {
    return MD5Sum< ::nodes::camera_get_info >::value();
  }
  static const char* value(const ::nodes::camera_get_infoResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::nodes::camera_get_infoResponse> should match 
// service_traits::DataType< ::nodes::camera_get_info > 
template<>
struct DataType< ::nodes::camera_get_infoResponse>
{
  static const char* value()
  {
    return DataType< ::nodes::camera_get_info >::value();
  }
  static const char* value(const ::nodes::camera_get_infoResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // NODES_MESSAGE_CAMERA_GET_INFO_H
