// Generated by gencpp from file nodes/camera_save_image.msg
// DO NOT EDIT!


#ifndef NODES_MESSAGE_CAMERA_SAVE_IMAGE_H
#define NODES_MESSAGE_CAMERA_SAVE_IMAGE_H

#include <ros/service_traits.h>


#include <nodes/camera_save_imageRequest.h>
#include <nodes/camera_save_imageResponse.h>


namespace nodes
{

struct camera_save_image
{

typedef camera_save_imageRequest Request;
typedef camera_save_imageResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct camera_save_image
} // namespace nodes


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::nodes::camera_save_image > {
  static const char* value()
  {
    return "9f4c973c7b1d0924ab26586269d7499e";
  }

  static const char* value(const ::nodes::camera_save_image&) { return value(); }
};

template<>
struct DataType< ::nodes::camera_save_image > {
  static const char* value()
  {
    return "nodes/camera_save_image";
  }

  static const char* value(const ::nodes::camera_save_image&) { return value(); }
};


// service_traits::MD5Sum< ::nodes::camera_save_imageRequest> should match 
// service_traits::MD5Sum< ::nodes::camera_save_image > 
template<>
struct MD5Sum< ::nodes::camera_save_imageRequest>
{
  static const char* value()
  {
    return MD5Sum< ::nodes::camera_save_image >::value();
  }
  static const char* value(const ::nodes::camera_save_imageRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::nodes::camera_save_imageRequest> should match 
// service_traits::DataType< ::nodes::camera_save_image > 
template<>
struct DataType< ::nodes::camera_save_imageRequest>
{
  static const char* value()
  {
    return DataType< ::nodes::camera_save_image >::value();
  }
  static const char* value(const ::nodes::camera_save_imageRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::nodes::camera_save_imageResponse> should match 
// service_traits::MD5Sum< ::nodes::camera_save_image > 
template<>
struct MD5Sum< ::nodes::camera_save_imageResponse>
{
  static const char* value()
  {
    return MD5Sum< ::nodes::camera_save_image >::value();
  }
  static const char* value(const ::nodes::camera_save_imageResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::nodes::camera_save_imageResponse> should match 
// service_traits::DataType< ::nodes::camera_save_image > 
template<>
struct DataType< ::nodes::camera_save_imageResponse>
{
  static const char* value()
  {
    return DataType< ::nodes::camera_save_image >::value();
  }
  static const char* value(const ::nodes::camera_save_imageResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // NODES_MESSAGE_CAMERA_SAVE_IMAGE_H
