// Generated by gencpp from file nodes/connector_get_presenceResponse.msg
// DO NOT EDIT!


#ifndef NODES_MESSAGE_CONNECTOR_GET_PRESENCERESPONSE_H
#define NODES_MESSAGE_CONNECTOR_GET_PRESENCERESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace nodes
{
template <class ContainerAllocator>
struct connector_get_presenceResponse_
{
  typedef connector_get_presenceResponse_<ContainerAllocator> Type;

  connector_get_presenceResponse_()
    : presence(0)  {
    }
  connector_get_presenceResponse_(const ContainerAllocator& _alloc)
    : presence(0)  {
    }



   typedef int8_t _presence_type;
  _presence_type presence;




  typedef boost::shared_ptr< ::nodes::connector_get_presenceResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::nodes::connector_get_presenceResponse_<ContainerAllocator> const> ConstPtr;

}; // struct connector_get_presenceResponse_

typedef ::nodes::connector_get_presenceResponse_<std::allocator<void> > connector_get_presenceResponse;

typedef boost::shared_ptr< ::nodes::connector_get_presenceResponse > connector_get_presenceResponsePtr;
typedef boost::shared_ptr< ::nodes::connector_get_presenceResponse const> connector_get_presenceResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::nodes::connector_get_presenceResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::nodes::connector_get_presenceResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace nodes

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'nodes': ['/home/legged/tns_ros1/controllers/joystick/catkin_ws/src/nodes/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::nodes::connector_get_presenceResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::nodes::connector_get_presenceResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::nodes::connector_get_presenceResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::nodes::connector_get_presenceResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::nodes::connector_get_presenceResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::nodes::connector_get_presenceResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::nodes::connector_get_presenceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "46141a1b2a9f40123c49bfa146a55c3d";
  }

  static const char* value(const ::nodes::connector_get_presenceResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x46141a1b2a9f4012ULL;
  static const uint64_t static_value2 = 0x3c49bfa146a55c3dULL;
};

template<class ContainerAllocator>
struct DataType< ::nodes::connector_get_presenceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "nodes/connector_get_presenceResponse";
  }

  static const char* value(const ::nodes::connector_get_presenceResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::nodes::connector_get_presenceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int8 presence\n\
\n\
";
  }

  static const char* value(const ::nodes::connector_get_presenceResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::nodes::connector_get_presenceResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.presence);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct connector_get_presenceResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::nodes::connector_get_presenceResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::nodes::connector_get_presenceResponse_<ContainerAllocator>& v)
  {
    s << indent << "presence: ";
    Printer<int8_t>::stream(s, indent + "  ", v.presence);
  }
};

} // namespace message_operations
} // namespace ros

#endif // NODES_MESSAGE_CONNECTOR_GET_PRESENCERESPONSE_H
