// Generated by gencpp from file nodes/connector_lock.msg
// DO NOT EDIT!


#ifndef NODES_MESSAGE_CONNECTOR_LOCK_H
#define NODES_MESSAGE_CONNECTOR_LOCK_H

#include <ros/service_traits.h>


#include <nodes/connector_lockRequest.h>
#include <nodes/connector_lockResponse.h>


namespace nodes
{

struct connector_lock
{

typedef connector_lockRequest Request;
typedef connector_lockResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct connector_lock
} // namespace nodes


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::nodes::connector_lock > {
  static const char* value()
  {
    return "e8ef0421913a1a27fc485b008f1602fa";
  }

  static const char* value(const ::nodes::connector_lock&) { return value(); }
};

template<>
struct DataType< ::nodes::connector_lock > {
  static const char* value()
  {
    return "nodes/connector_lock";
  }

  static const char* value(const ::nodes::connector_lock&) { return value(); }
};


// service_traits::MD5Sum< ::nodes::connector_lockRequest> should match 
// service_traits::MD5Sum< ::nodes::connector_lock > 
template<>
struct MD5Sum< ::nodes::connector_lockRequest>
{
  static const char* value()
  {
    return MD5Sum< ::nodes::connector_lock >::value();
  }
  static const char* value(const ::nodes::connector_lockRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::nodes::connector_lockRequest> should match 
// service_traits::DataType< ::nodes::connector_lock > 
template<>
struct DataType< ::nodes::connector_lockRequest>
{
  static const char* value()
  {
    return DataType< ::nodes::connector_lock >::value();
  }
  static const char* value(const ::nodes::connector_lockRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::nodes::connector_lockResponse> should match 
// service_traits::MD5Sum< ::nodes::connector_lock > 
template<>
struct MD5Sum< ::nodes::connector_lockResponse>
{
  static const char* value()
  {
    return MD5Sum< ::nodes::connector_lock >::value();
  }
  static const char* value(const ::nodes::connector_lockResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::nodes::connector_lockResponse> should match 
// service_traits::DataType< ::nodes::connector_lock > 
template<>
struct DataType< ::nodes::connector_lockResponse>
{
  static const char* value()
  {
    return DataType< ::nodes::connector_lock >::value();
  }
  static const char* value(const ::nodes::connector_lockResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // NODES_MESSAGE_CONNECTOR_LOCK_H
