// Generated by gencpp from file nodes/connector_set_presenceRequest.msg
// DO NOT EDIT!


#ifndef NODES_MESSAGE_CONNECTOR_SET_PRESENCEREQUEST_H
#define NODES_MESSAGE_CONNECTOR_SET_PRESENCEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace nodes
{
template <class ContainerAllocator>
struct connector_set_presenceRequest_
{
  typedef connector_set_presenceRequest_<ContainerAllocator> Type;

  connector_set_presenceRequest_()
    : period(0)  {
    }
  connector_set_presenceRequest_(const ContainerAllocator& _alloc)
    : period(0)  {
    }



   typedef int32_t _period_type;
  _period_type period;




  typedef boost::shared_ptr< ::nodes::connector_set_presenceRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::nodes::connector_set_presenceRequest_<ContainerAllocator> const> ConstPtr;

}; // struct connector_set_presenceRequest_

typedef ::nodes::connector_set_presenceRequest_<std::allocator<void> > connector_set_presenceRequest;

typedef boost::shared_ptr< ::nodes::connector_set_presenceRequest > connector_set_presenceRequestPtr;
typedef boost::shared_ptr< ::nodes::connector_set_presenceRequest const> connector_set_presenceRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::nodes::connector_set_presenceRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::nodes::connector_set_presenceRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace nodes

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'nodes': ['/home/legged/tns_ros1/controllers/joystick/catkin_ws/src/nodes/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::nodes::connector_set_presenceRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::nodes::connector_set_presenceRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::nodes::connector_set_presenceRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::nodes::connector_set_presenceRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::nodes::connector_set_presenceRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::nodes::connector_set_presenceRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::nodes::connector_set_presenceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6d22728fab3193630575656addb2f2a7";
  }

  static const char* value(const ::nodes::connector_set_presenceRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6d22728fab319363ULL;
  static const uint64_t static_value2 = 0x0575656addb2f2a7ULL;
};

template<class ContainerAllocator>
struct DataType< ::nodes::connector_set_presenceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "nodes/connector_set_presenceRequest";
  }

  static const char* value(const ::nodes::connector_set_presenceRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::nodes::connector_set_presenceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 period\n\
";
  }

  static const char* value(const ::nodes::connector_set_presenceRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::nodes::connector_set_presenceRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.period);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct connector_set_presenceRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::nodes::connector_set_presenceRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::nodes::connector_set_presenceRequest_<ContainerAllocator>& v)
  {
    s << indent << "period: ";
    Printer<int32_t>::stream(s, indent + "  ", v.period);
  }
};

} // namespace message_operations
} // namespace ros

#endif // NODES_MESSAGE_CONNECTOR_SET_PRESENCEREQUEST_H
