// Generated by gencpp from file nodes/differential_wheels_enable_control.msg
// DO NOT EDIT!


#ifndef NODES_MESSAGE_DIFFERENTIAL_WHEELS_ENABLE_CONTROL_H
#define NODES_MESSAGE_DIFFERENTIAL_WHEELS_ENABLE_CONTROL_H

#include <ros/service_traits.h>


#include <nodes/differential_wheels_enable_controlRequest.h>
#include <nodes/differential_wheels_enable_controlResponse.h>


namespace nodes
{

struct differential_wheels_enable_control
{

typedef differential_wheels_enable_controlRequest Request;
typedef differential_wheels_enable_controlResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct differential_wheels_enable_control
} // namespace nodes


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::nodes::differential_wheels_enable_control > {
  static const char* value()
  {
    return "afc85352ca2bea8ffa30f931a12de254";
  }

  static const char* value(const ::nodes::differential_wheels_enable_control&) { return value(); }
};

template<>
struct DataType< ::nodes::differential_wheels_enable_control > {
  static const char* value()
  {
    return "nodes/differential_wheels_enable_control";
  }

  static const char* value(const ::nodes::differential_wheels_enable_control&) { return value(); }
};


// service_traits::MD5Sum< ::nodes::differential_wheels_enable_controlRequest> should match 
// service_traits::MD5Sum< ::nodes::differential_wheels_enable_control > 
template<>
struct MD5Sum< ::nodes::differential_wheels_enable_controlRequest>
{
  static const char* value()
  {
    return MD5Sum< ::nodes::differential_wheels_enable_control >::value();
  }
  static const char* value(const ::nodes::differential_wheels_enable_controlRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::nodes::differential_wheels_enable_controlRequest> should match 
// service_traits::DataType< ::nodes::differential_wheels_enable_control > 
template<>
struct DataType< ::nodes::differential_wheels_enable_controlRequest>
{
  static const char* value()
  {
    return DataType< ::nodes::differential_wheels_enable_control >::value();
  }
  static const char* value(const ::nodes::differential_wheels_enable_controlRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::nodes::differential_wheels_enable_controlResponse> should match 
// service_traits::MD5Sum< ::nodes::differential_wheels_enable_control > 
template<>
struct MD5Sum< ::nodes::differential_wheels_enable_controlResponse>
{
  static const char* value()
  {
    return MD5Sum< ::nodes::differential_wheels_enable_control >::value();
  }
  static const char* value(const ::nodes::differential_wheels_enable_controlResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::nodes::differential_wheels_enable_controlResponse> should match 
// service_traits::DataType< ::nodes::differential_wheels_enable_control > 
template<>
struct DataType< ::nodes::differential_wheels_enable_controlResponse>
{
  static const char* value()
  {
    return DataType< ::nodes::differential_wheels_enable_control >::value();
  }
  static const char* value(const ::nodes::differential_wheels_enable_controlResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // NODES_MESSAGE_DIFFERENTIAL_WHEELS_ENABLE_CONTROL_H
