// Generated by gencpp from file nodes/differential_wheels_enable_controlRequest.msg
// DO NOT EDIT!


#ifndef NODES_MESSAGE_DIFFERENTIAL_WHEELS_ENABLE_CONTROLREQUEST_H
#define NODES_MESSAGE_DIFFERENTIAL_WHEELS_ENABLE_CONTROLREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace nodes
{
template <class ContainerAllocator>
struct differential_wheels_enable_controlRequest_
{
  typedef differential_wheels_enable_controlRequest_<ContainerAllocator> Type;

  differential_wheels_enable_controlRequest_()
    : enable(0)  {
    }
  differential_wheels_enable_controlRequest_(const ContainerAllocator& _alloc)
    : enable(0)  {
    }



   typedef uint8_t _enable_type;
  _enable_type enable;




  typedef boost::shared_ptr< ::nodes::differential_wheels_enable_controlRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::nodes::differential_wheels_enable_controlRequest_<ContainerAllocator> const> ConstPtr;

}; // struct differential_wheels_enable_controlRequest_

typedef ::nodes::differential_wheels_enable_controlRequest_<std::allocator<void> > differential_wheels_enable_controlRequest;

typedef boost::shared_ptr< ::nodes::differential_wheels_enable_controlRequest > differential_wheels_enable_controlRequestPtr;
typedef boost::shared_ptr< ::nodes::differential_wheels_enable_controlRequest const> differential_wheels_enable_controlRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::nodes::differential_wheels_enable_controlRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::nodes::differential_wheels_enable_controlRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace nodes

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'nodes': ['/home/legged/tns_ros1/controllers/joystick/catkin_ws/src/nodes/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::nodes::differential_wheels_enable_controlRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::nodes::differential_wheels_enable_controlRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::nodes::differential_wheels_enable_controlRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::nodes::differential_wheels_enable_controlRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::nodes::differential_wheels_enable_controlRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::nodes::differential_wheels_enable_controlRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::nodes::differential_wheels_enable_controlRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "34abd7794638063ef7576ad13e0da876";
  }

  static const char* value(const ::nodes::differential_wheels_enable_controlRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x34abd7794638063eULL;
  static const uint64_t static_value2 = 0xf7576ad13e0da876ULL;
};

template<class ContainerAllocator>
struct DataType< ::nodes::differential_wheels_enable_controlRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "nodes/differential_wheels_enable_controlRequest";
  }

  static const char* value(const ::nodes::differential_wheels_enable_controlRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::nodes::differential_wheels_enable_controlRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 enable\n\
";
  }

  static const char* value(const ::nodes::differential_wheels_enable_controlRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::nodes::differential_wheels_enable_controlRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.enable);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct differential_wheels_enable_controlRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::nodes::differential_wheels_enable_controlRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::nodes::differential_wheels_enable_controlRequest_<ContainerAllocator>& v)
  {
    s << indent << "enable: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.enable);
  }
};

} // namespace message_operations
} // namespace ros

#endif // NODES_MESSAGE_DIFFERENTIAL_WHEELS_ENABLE_CONTROLREQUEST_H
