// Generated by gencpp from file nodes/display_fill_oval.msg
// DO NOT EDIT!


#ifndef NODES_MESSAGE_DISPLAY_FILL_OVAL_H
#define NODES_MESSAGE_DISPLAY_FILL_OVAL_H

#include <ros/service_traits.h>


#include <nodes/display_fill_ovalRequest.h>
#include <nodes/display_fill_ovalResponse.h>


namespace nodes
{

struct display_fill_oval
{

typedef display_fill_ovalRequest Request;
typedef display_fill_ovalResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct display_fill_oval
} // namespace nodes


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::nodes::display_fill_oval > {
  static const char* value()
  {
    return "257804d9f2e4639bae589e190802d29f";
  }

  static const char* value(const ::nodes::display_fill_oval&) { return value(); }
};

template<>
struct DataType< ::nodes::display_fill_oval > {
  static const char* value()
  {
    return "nodes/display_fill_oval";
  }

  static const char* value(const ::nodes::display_fill_oval&) { return value(); }
};


// service_traits::MD5Sum< ::nodes::display_fill_ovalRequest> should match 
// service_traits::MD5Sum< ::nodes::display_fill_oval > 
template<>
struct MD5Sum< ::nodes::display_fill_ovalRequest>
{
  static const char* value()
  {
    return MD5Sum< ::nodes::display_fill_oval >::value();
  }
  static const char* value(const ::nodes::display_fill_ovalRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::nodes::display_fill_ovalRequest> should match 
// service_traits::DataType< ::nodes::display_fill_oval > 
template<>
struct DataType< ::nodes::display_fill_ovalRequest>
{
  static const char* value()
  {
    return DataType< ::nodes::display_fill_oval >::value();
  }
  static const char* value(const ::nodes::display_fill_ovalRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::nodes::display_fill_ovalResponse> should match 
// service_traits::MD5Sum< ::nodes::display_fill_oval > 
template<>
struct MD5Sum< ::nodes::display_fill_ovalResponse>
{
  static const char* value()
  {
    return MD5Sum< ::nodes::display_fill_oval >::value();
  }
  static const char* value(const ::nodes::display_fill_ovalResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::nodes::display_fill_ovalResponse> should match 
// service_traits::DataType< ::nodes::display_fill_oval > 
template<>
struct DataType< ::nodes::display_fill_ovalResponse>
{
  static const char* value()
  {
    return DataType< ::nodes::display_fill_oval >::value();
  }
  static const char* value(const ::nodes::display_fill_ovalResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // NODES_MESSAGE_DISPLAY_FILL_OVAL_H
