// Generated by gencpp from file nodes/display_fill_rectangleRequest.msg
// DO NOT EDIT!


#ifndef NODES_MESSAGE_DISPLAY_FILL_RECTANGLEREQUEST_H
#define NODES_MESSAGE_DISPLAY_FILL_RECTANGLEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace nodes
{
template <class ContainerAllocator>
struct display_fill_rectangleRequest_
{
  typedef display_fill_rectangleRequest_<ContainerAllocator> Type;

  display_fill_rectangleRequest_()
    : x(0)
    , y(0)
    , width(0)
    , height(0)  {
    }
  display_fill_rectangleRequest_(const ContainerAllocator& _alloc)
    : x(0)
    , y(0)
    , width(0)
    , height(0)  {
    }



   typedef int32_t _x_type;
  _x_type x;

   typedef int32_t _y_type;
  _y_type y;

   typedef int32_t _width_type;
  _width_type width;

   typedef int32_t _height_type;
  _height_type height;




  typedef boost::shared_ptr< ::nodes::display_fill_rectangleRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::nodes::display_fill_rectangleRequest_<ContainerAllocator> const> ConstPtr;

}; // struct display_fill_rectangleRequest_

typedef ::nodes::display_fill_rectangleRequest_<std::allocator<void> > display_fill_rectangleRequest;

typedef boost::shared_ptr< ::nodes::display_fill_rectangleRequest > display_fill_rectangleRequestPtr;
typedef boost::shared_ptr< ::nodes::display_fill_rectangleRequest const> display_fill_rectangleRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::nodes::display_fill_rectangleRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::nodes::display_fill_rectangleRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace nodes

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'nodes': ['/home/legged/tns_ros1/controllers/joystick/catkin_ws/src/nodes/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::nodes::display_fill_rectangleRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::nodes::display_fill_rectangleRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::nodes::display_fill_rectangleRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::nodes::display_fill_rectangleRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::nodes::display_fill_rectangleRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::nodes::display_fill_rectangleRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::nodes::display_fill_rectangleRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4425f1067abc7ec2e487d28194eccff4";
  }

  static const char* value(const ::nodes::display_fill_rectangleRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4425f1067abc7ec2ULL;
  static const uint64_t static_value2 = 0xe487d28194eccff4ULL;
};

template<class ContainerAllocator>
struct DataType< ::nodes::display_fill_rectangleRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "nodes/display_fill_rectangleRequest";
  }

  static const char* value(const ::nodes::display_fill_rectangleRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::nodes::display_fill_rectangleRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 x\n\
int32 y\n\
int32 width\n\
int32 height\n\
";
  }

  static const char* value(const ::nodes::display_fill_rectangleRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::nodes::display_fill_rectangleRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.width);
      stream.next(m.height);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct display_fill_rectangleRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::nodes::display_fill_rectangleRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::nodes::display_fill_rectangleRequest_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<int32_t>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<int32_t>::stream(s, indent + "  ", v.y);
    s << indent << "width: ";
    Printer<int32_t>::stream(s, indent + "  ", v.width);
    s << indent << "height: ";
    Printer<int32_t>::stream(s, indent + "  ", v.height);
  }
};

} // namespace message_operations
} // namespace ros

#endif // NODES_MESSAGE_DISPLAY_FILL_RECTANGLEREQUEST_H
