// Generated by gencpp from file nodes/display_set_color.msg
// DO NOT EDIT!


#ifndef NODES_MESSAGE_DISPLAY_SET_COLOR_H
#define NODES_MESSAGE_DISPLAY_SET_COLOR_H

#include <ros/service_traits.h>


#include <nodes/display_set_colorRequest.h>
#include <nodes/display_set_colorResponse.h>


namespace nodes
{

struct display_set_color
{

typedef display_set_colorRequest Request;
typedef display_set_colorResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct display_set_color
} // namespace nodes


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::nodes::display_set_color > {
  static const char* value()
  {
    return "56cea22e280c0030806ba10faba23442";
  }

  static const char* value(const ::nodes::display_set_color&) { return value(); }
};

template<>
struct DataType< ::nodes::display_set_color > {
  static const char* value()
  {
    return "nodes/display_set_color";
  }

  static const char* value(const ::nodes::display_set_color&) { return value(); }
};


// service_traits::MD5Sum< ::nodes::display_set_colorRequest> should match 
// service_traits::MD5Sum< ::nodes::display_set_color > 
template<>
struct MD5Sum< ::nodes::display_set_colorRequest>
{
  static const char* value()
  {
    return MD5Sum< ::nodes::display_set_color >::value();
  }
  static const char* value(const ::nodes::display_set_colorRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::nodes::display_set_colorRequest> should match 
// service_traits::DataType< ::nodes::display_set_color > 
template<>
struct DataType< ::nodes::display_set_colorRequest>
{
  static const char* value()
  {
    return DataType< ::nodes::display_set_color >::value();
  }
  static const char* value(const ::nodes::display_set_colorRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::nodes::display_set_colorResponse> should match 
// service_traits::MD5Sum< ::nodes::display_set_color > 
template<>
struct MD5Sum< ::nodes::display_set_colorResponse>
{
  static const char* value()
  {
    return MD5Sum< ::nodes::display_set_color >::value();
  }
  static const char* value(const ::nodes::display_set_colorResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::nodes::display_set_colorResponse> should match 
// service_traits::DataType< ::nodes::display_set_color > 
template<>
struct DataType< ::nodes::display_set_colorResponse>
{
  static const char* value()
  {
    return DataType< ::nodes::display_set_color >::value();
  }
  static const char* value(const ::nodes::display_set_colorResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // NODES_MESSAGE_DISPLAY_SET_COLOR_H
