// Generated by gencpp from file nodes/display_set_opacityRequest.msg
// DO NOT EDIT!


#ifndef NODES_MESSAGE_DISPLAY_SET_OPACITYREQUEST_H
#define NODES_MESSAGE_DISPLAY_SET_OPACITYREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace nodes
{
template <class ContainerAllocator>
struct display_set_opacityRequest_
{
  typedef display_set_opacityRequest_<ContainerAllocator> Type;

  display_set_opacityRequest_()
    : opacity(0.0)  {
    }
  display_set_opacityRequest_(const ContainerAllocator& _alloc)
    : opacity(0.0)  {
    }



   typedef double _opacity_type;
  _opacity_type opacity;




  typedef boost::shared_ptr< ::nodes::display_set_opacityRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::nodes::display_set_opacityRequest_<ContainerAllocator> const> ConstPtr;

}; // struct display_set_opacityRequest_

typedef ::nodes::display_set_opacityRequest_<std::allocator<void> > display_set_opacityRequest;

typedef boost::shared_ptr< ::nodes::display_set_opacityRequest > display_set_opacityRequestPtr;
typedef boost::shared_ptr< ::nodes::display_set_opacityRequest const> display_set_opacityRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::nodes::display_set_opacityRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::nodes::display_set_opacityRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace nodes

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'nodes': ['/home/legged/tns_ros1/controllers/joystick/catkin_ws/src/nodes/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::nodes::display_set_opacityRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::nodes::display_set_opacityRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::nodes::display_set_opacityRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::nodes::display_set_opacityRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::nodes::display_set_opacityRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::nodes::display_set_opacityRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::nodes::display_set_opacityRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "814cc6109b1cfab505ea8bf128ca3d86";
  }

  static const char* value(const ::nodes::display_set_opacityRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x814cc6109b1cfab5ULL;
  static const uint64_t static_value2 = 0x05ea8bf128ca3d86ULL;
};

template<class ContainerAllocator>
struct DataType< ::nodes::display_set_opacityRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "nodes/display_set_opacityRequest";
  }

  static const char* value(const ::nodes::display_set_opacityRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::nodes::display_set_opacityRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 opacity\n\
";
  }

  static const char* value(const ::nodes::display_set_opacityRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::nodes::display_set_opacityRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.opacity);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct display_set_opacityRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::nodes::display_set_opacityRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::nodes::display_set_opacityRequest_<ContainerAllocator>& v)
  {
    s << indent << "opacity: ";
    Printer<double>::stream(s, indent + "  ", v.opacity);
  }
};

} // namespace message_operations
} // namespace ros

#endif // NODES_MESSAGE_DISPLAY_SET_OPACITYREQUEST_H
