// Generated by gencpp from file nodes/display_fill_rectangle.msg
// DO NOT EDIT!


#ifndef NODES_MESSAGE_DISPLAY_FILL_RECTANGLE_H
#define NODES_MESSAGE_DISPLAY_FILL_RECTANGLE_H

#include <ros/service_traits.h>


#include <nodes/display_fill_rectangleRequest.h>
#include <nodes/display_fill_rectangleResponse.h>


namespace nodes
{

struct display_fill_rectangle
{

typedef display_fill_rectangleRequest Request;
typedef display_fill_rectangleResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct display_fill_rectangle
} // namespace nodes


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::nodes::display_fill_rectangle > {
  static const char* value()
  {
    return "f7d77dd6f16a5d7e8ba643de53791446";
  }

  static const char* value(const ::nodes::display_fill_rectangle&) { return value(); }
};

template<>
struct DataType< ::nodes::display_fill_rectangle > {
  static const char* value()
  {
    return "nodes/display_fill_rectangle";
  }

  static const char* value(const ::nodes::display_fill_rectangle&) { return value(); }
};


// service_traits::MD5Sum< ::nodes::display_fill_rectangleRequest> should match 
// service_traits::MD5Sum< ::nodes::display_fill_rectangle > 
template<>
struct MD5Sum< ::nodes::display_fill_rectangleRequest>
{
  static const char* value()
  {
    return MD5Sum< ::nodes::display_fill_rectangle >::value();
  }
  static const char* value(const ::nodes::display_fill_rectangleRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::nodes::display_fill_rectangleRequest> should match 
// service_traits::DataType< ::nodes::display_fill_rectangle > 
template<>
struct DataType< ::nodes::display_fill_rectangleRequest>
{
  static const char* value()
  {
    return DataType< ::nodes::display_fill_rectangle >::value();
  }
  static const char* value(const ::nodes::display_fill_rectangleRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::nodes::display_fill_rectangleResponse> should match 
// service_traits::MD5Sum< ::nodes::display_fill_rectangle > 
template<>
struct MD5Sum< ::nodes::display_fill_rectangleResponse>
{
  static const char* value()
  {
    return MD5Sum< ::nodes::display_fill_rectangle >::value();
  }
  static const char* value(const ::nodes::display_fill_rectangleResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::nodes::display_fill_rectangleResponse> should match 
// service_traits::DataType< ::nodes::display_fill_rectangle > 
template<>
struct DataType< ::nodes::display_fill_rectangleResponse>
{
  static const char* value()
  {
    return DataType< ::nodes::display_fill_rectangle >::value();
  }
  static const char* value(const ::nodes::display_fill_rectangleResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // NODES_MESSAGE_DISPLAY_FILL_RECTANGLE_H
