// Generated by gencpp from file nodes/display_draw_line.msg
// DO NOT EDIT!


#ifndef NODES_MESSAGE_DISPLAY_DRAW_LINE_H
#define NODES_MESSAGE_DISPLAY_DRAW_LINE_H

#include <ros/service_traits.h>


#include <nodes/display_draw_lineRequest.h>
#include <nodes/display_draw_lineResponse.h>


namespace nodes
{

struct display_draw_line
{

typedef display_draw_lineRequest Request;
typedef display_draw_lineResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct display_draw_line
} // namespace nodes


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::nodes::display_draw_line > {
  static const char* value()
  {
    return "67df0d281bcb1579baa48d1202f84ebe";
  }

  static const char* value(const ::nodes::display_draw_line&) { return value(); }
};

template<>
struct DataType< ::nodes::display_draw_line > {
  static const char* value()
  {
    return "nodes/display_draw_line";
  }

  static const char* value(const ::nodes::display_draw_line&) { return value(); }
};


// service_traits::MD5Sum< ::nodes::display_draw_lineRequest> should match 
// service_traits::MD5Sum< ::nodes::display_draw_line > 
template<>
struct MD5Sum< ::nodes::display_draw_lineRequest>
{
  static const char* value()
  {
    return MD5Sum< ::nodes::display_draw_line >::value();
  }
  static const char* value(const ::nodes::display_draw_lineRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::nodes::display_draw_lineRequest> should match 
// service_traits::DataType< ::nodes::display_draw_line > 
template<>
struct DataType< ::nodes::display_draw_lineRequest>
{
  static const char* value()
  {
    return DataType< ::nodes::display_draw_line >::value();
  }
  static const char* value(const ::nodes::display_draw_lineRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::nodes::display_draw_lineResponse> should match 
// service_traits::MD5Sum< ::nodes::display_draw_line > 
template<>
struct MD5Sum< ::nodes::display_draw_lineResponse>
{
  static const char* value()
  {
    return MD5Sum< ::nodes::display_draw_line >::value();
  }
  static const char* value(const ::nodes::display_draw_lineResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::nodes::display_draw_lineResponse> should match 
// service_traits::DataType< ::nodes::display_draw_line > 
template<>
struct DataType< ::nodes::display_draw_lineResponse>
{
  static const char* value()
  {
    return DataType< ::nodes::display_draw_line >::value();
  }
  static const char* value(const ::nodes::display_draw_lineResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // NODES_MESSAGE_DISPLAY_DRAW_LINE_H
