// Generated by gencpp from file nodes/display_set_alpha.msg
// DO NOT EDIT!


#ifndef NODES_MESSAGE_DISPLAY_SET_ALPHA_H
#define NODES_MESSAGE_DISPLAY_SET_ALPHA_H

#include <ros/service_traits.h>


#include <nodes/display_set_alphaRequest.h>
#include <nodes/display_set_alphaResponse.h>


namespace nodes
{

struct display_set_alpha
{

typedef display_set_alphaRequest Request;
typedef display_set_alphaResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct display_set_alpha
} // namespace nodes


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::nodes::display_set_alpha > {
  static const char* value()
  {
    return "056ae584611f84e9939478d7bba711d1";
  }

  static const char* value(const ::nodes::display_set_alpha&) { return value(); }
};

template<>
struct DataType< ::nodes::display_set_alpha > {
  static const char* value()
  {
    return "nodes/display_set_alpha";
  }

  static const char* value(const ::nodes::display_set_alpha&) { return value(); }
};


// service_traits::MD5Sum< ::nodes::display_set_alphaRequest> should match 
// service_traits::MD5Sum< ::nodes::display_set_alpha > 
template<>
struct MD5Sum< ::nodes::display_set_alphaRequest>
{
  static const char* value()
  {
    return MD5Sum< ::nodes::display_set_alpha >::value();
  }
  static const char* value(const ::nodes::display_set_alphaRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::nodes::display_set_alphaRequest> should match 
// service_traits::DataType< ::nodes::display_set_alpha > 
template<>
struct DataType< ::nodes::display_set_alphaRequest>
{
  static const char* value()
  {
    return DataType< ::nodes::display_set_alpha >::value();
  }
  static const char* value(const ::nodes::display_set_alphaRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::nodes::display_set_alphaResponse> should match 
// service_traits::MD5Sum< ::nodes::display_set_alpha > 
template<>
struct MD5Sum< ::nodes::display_set_alphaResponse>
{
  static const char* value()
  {
    return MD5Sum< ::nodes::display_set_alpha >::value();
  }
  static const char* value(const ::nodes::display_set_alphaResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::nodes::display_set_alphaResponse> should match 
// service_traits::DataType< ::nodes::display_set_alpha > 
template<>
struct DataType< ::nodes::display_set_alphaResponse>
{
  static const char* value()
  {
    return DataType< ::nodes::display_set_alpha >::value();
  }
  static const char* value(const ::nodes::display_set_alphaResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // NODES_MESSAGE_DISPLAY_SET_ALPHA_H
