// Generated by gencpp from file nodes/display_set_opacity.msg
// DO NOT EDIT!


#ifndef NODES_MESSAGE_DISPLAY_SET_OPACITY_H
#define NODES_MESSAGE_DISPLAY_SET_OPACITY_H

#include <ros/service_traits.h>


#include <nodes/display_set_opacityRequest.h>
#include <nodes/display_set_opacityResponse.h>


namespace nodes
{

struct display_set_opacity
{

typedef display_set_opacityRequest Request;
typedef display_set_opacityResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct display_set_opacity
} // namespace nodes


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::nodes::display_set_opacity > {
  static const char* value()
  {
    return "4cd98a3152470bde07621c10fe0fea7d";
  }

  static const char* value(const ::nodes::display_set_opacity&) { return value(); }
};

template<>
struct DataType< ::nodes::display_set_opacity > {
  static const char* value()
  {
    return "nodes/display_set_opacity";
  }

  static const char* value(const ::nodes::display_set_opacity&) { return value(); }
};


// service_traits::MD5Sum< ::nodes::display_set_opacityRequest> should match 
// service_traits::MD5Sum< ::nodes::display_set_opacity > 
template<>
struct MD5Sum< ::nodes::display_set_opacityRequest>
{
  static const char* value()
  {
    return MD5Sum< ::nodes::display_set_opacity >::value();
  }
  static const char* value(const ::nodes::display_set_opacityRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::nodes::display_set_opacityRequest> should match 
// service_traits::DataType< ::nodes::display_set_opacity > 
template<>
struct DataType< ::nodes::display_set_opacityRequest>
{
  static const char* value()
  {
    return DataType< ::nodes::display_set_opacity >::value();
  }
  static const char* value(const ::nodes::display_set_opacityRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::nodes::display_set_opacityResponse> should match 
// service_traits::MD5Sum< ::nodes::display_set_opacity > 
template<>
struct MD5Sum< ::nodes::display_set_opacityResponse>
{
  static const char* value()
  {
    return MD5Sum< ::nodes::display_set_opacity >::value();
  }
  static const char* value(const ::nodes::display_set_opacityResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::nodes::display_set_opacityResponse> should match 
// service_traits::DataType< ::nodes::display_set_opacity > 
template<>
struct DataType< ::nodes::display_set_opacityResponse>
{
  static const char* value()
  {
    return DataType< ::nodes::display_set_opacity >::value();
  }
  static const char* value(const ::nodes::display_set_opacityResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // NODES_MESSAGE_DISPLAY_SET_OPACITY_H
