// Generated by gencpp from file nodes/field_get_vec3f.msg
// DO NOT EDIT!


#ifndef NODES_MESSAGE_FIELD_GET_VEC3F_H
#define NODES_MESSAGE_FIELD_GET_VEC3F_H

#include <ros/service_traits.h>


#include <nodes/field_get_vec3fRequest.h>
#include <nodes/field_get_vec3fResponse.h>


namespace nodes
{

struct field_get_vec3f
{

typedef field_get_vec3fRequest Request;
typedef field_get_vec3fResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct field_get_vec3f
} // namespace nodes


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::nodes::field_get_vec3f > {
  static const char* value()
  {
    return "c36551ebe8006c17263cf88ddd9352b3";
  }

  static const char* value(const ::nodes::field_get_vec3f&) { return value(); }
};

template<>
struct DataType< ::nodes::field_get_vec3f > {
  static const char* value()
  {
    return "nodes/field_get_vec3f";
  }

  static const char* value(const ::nodes::field_get_vec3f&) { return value(); }
};


// service_traits::MD5Sum< ::nodes::field_get_vec3fRequest> should match 
// service_traits::MD5Sum< ::nodes::field_get_vec3f > 
template<>
struct MD5Sum< ::nodes::field_get_vec3fRequest>
{
  static const char* value()
  {
    return MD5Sum< ::nodes::field_get_vec3f >::value();
  }
  static const char* value(const ::nodes::field_get_vec3fRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::nodes::field_get_vec3fRequest> should match 
// service_traits::DataType< ::nodes::field_get_vec3f > 
template<>
struct DataType< ::nodes::field_get_vec3fRequest>
{
  static const char* value()
  {
    return DataType< ::nodes::field_get_vec3f >::value();
  }
  static const char* value(const ::nodes::field_get_vec3fRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::nodes::field_get_vec3fResponse> should match 
// service_traits::MD5Sum< ::nodes::field_get_vec3f > 
template<>
struct MD5Sum< ::nodes::field_get_vec3fResponse>
{
  static const char* value()
  {
    return MD5Sum< ::nodes::field_get_vec3f >::value();
  }
  static const char* value(const ::nodes::field_get_vec3fResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::nodes::field_get_vec3fResponse> should match 
// service_traits::DataType< ::nodes::field_get_vec3f > 
template<>
struct DataType< ::nodes::field_get_vec3fResponse>
{
  static const char* value()
  {
    return DataType< ::nodes::field_get_vec3f >::value();
  }
  static const char* value(const ::nodes::field_get_vec3fResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // NODES_MESSAGE_FIELD_GET_VEC3F_H
