// Generated by gencpp from file nodes/field_set_vec2f.msg
// DO NOT EDIT!


#ifndef NODES_MESSAGE_FIELD_SET_VEC2F_H
#define NODES_MESSAGE_FIELD_SET_VEC2F_H

#include <ros/service_traits.h>


#include <nodes/field_set_vec2fRequest.h>
#include <nodes/field_set_vec2fResponse.h>


namespace nodes
{

struct field_set_vec2f
{

typedef field_set_vec2fRequest Request;
typedef field_set_vec2fResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct field_set_vec2f
} // namespace nodes


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::nodes::field_set_vec2f > {
  static const char* value()
  {
    return "7411ef8c86bf7a3ab6da3c99d7f5aae2";
  }

  static const char* value(const ::nodes::field_set_vec2f&) { return value(); }
};

template<>
struct DataType< ::nodes::field_set_vec2f > {
  static const char* value()
  {
    return "nodes/field_set_vec2f";
  }

  static const char* value(const ::nodes::field_set_vec2f&) { return value(); }
};


// service_traits::MD5Sum< ::nodes::field_set_vec2fRequest> should match 
// service_traits::MD5Sum< ::nodes::field_set_vec2f > 
template<>
struct MD5Sum< ::nodes::field_set_vec2fRequest>
{
  static const char* value()
  {
    return MD5Sum< ::nodes::field_set_vec2f >::value();
  }
  static const char* value(const ::nodes::field_set_vec2fRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::nodes::field_set_vec2fRequest> should match 
// service_traits::DataType< ::nodes::field_set_vec2f > 
template<>
struct DataType< ::nodes::field_set_vec2fRequest>
{
  static const char* value()
  {
    return DataType< ::nodes::field_set_vec2f >::value();
  }
  static const char* value(const ::nodes::field_set_vec2fRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::nodes::field_set_vec2fResponse> should match 
// service_traits::MD5Sum< ::nodes::field_set_vec2f > 
template<>
struct MD5Sum< ::nodes::field_set_vec2fResponse>
{
  static const char* value()
  {
    return MD5Sum< ::nodes::field_set_vec2f >::value();
  }
  static const char* value(const ::nodes::field_set_vec2fResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::nodes::field_set_vec2fResponse> should match 
// service_traits::DataType< ::nodes::field_set_vec2f > 
template<>
struct DataType< ::nodes::field_set_vec2fResponse>
{
  static const char* value()
  {
    return DataType< ::nodes::field_set_vec2f >::value();
  }
  static const char* value(const ::nodes::field_set_vec2fResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // NODES_MESSAGE_FIELD_SET_VEC2F_H
