// Generated by gencpp from file nodes/led_get.msg
// DO NOT EDIT!


#ifndef NODES_MESSAGE_LED_GET_H
#define NODES_MESSAGE_LED_GET_H

#include <ros/service_traits.h>


#include <nodes/led_getRequest.h>
#include <nodes/led_getResponse.h>


namespace nodes
{

struct led_get
{

typedef led_getRequest Request;
typedef led_getResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct led_get
} // namespace nodes


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::nodes::led_get > {
  static const char* value()
  {
    return "709a80151e44785f1eda351c08f2f190";
  }

  static const char* value(const ::nodes::led_get&) { return value(); }
};

template<>
struct DataType< ::nodes::led_get > {
  static const char* value()
  {
    return "nodes/led_get";
  }

  static const char* value(const ::nodes::led_get&) { return value(); }
};


// service_traits::MD5Sum< ::nodes::led_getRequest> should match 
// service_traits::MD5Sum< ::nodes::led_get > 
template<>
struct MD5Sum< ::nodes::led_getRequest>
{
  static const char* value()
  {
    return MD5Sum< ::nodes::led_get >::value();
  }
  static const char* value(const ::nodes::led_getRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::nodes::led_getRequest> should match 
// service_traits::DataType< ::nodes::led_get > 
template<>
struct DataType< ::nodes::led_getRequest>
{
  static const char* value()
  {
    return DataType< ::nodes::led_get >::value();
  }
  static const char* value(const ::nodes::led_getRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::nodes::led_getResponse> should match 
// service_traits::MD5Sum< ::nodes::led_get > 
template<>
struct MD5Sum< ::nodes::led_getResponse>
{
  static const char* value()
  {
    return MD5Sum< ::nodes::led_get >::value();
  }
  static const char* value(const ::nodes::led_getResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::nodes::led_getResponse> should match 
// service_traits::DataType< ::nodes::led_get > 
template<>
struct DataType< ::nodes::led_getResponse>
{
  static const char* value()
  {
    return DataType< ::nodes::led_get >::value();
  }
  static const char* value(const ::nodes::led_getResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // NODES_MESSAGE_LED_GET_H
