// Generated by gencpp from file nodes/motor_get_min_positionResponse.msg
// DO NOT EDIT!


#ifndef NODES_MESSAGE_MOTOR_GET_MIN_POSITIONRESPONSE_H
#define NODES_MESSAGE_MOTOR_GET_MIN_POSITIONRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace nodes
{
template <class ContainerAllocator>
struct motor_get_min_positionResponse_
{
  typedef motor_get_min_positionResponse_<ContainerAllocator> Type;

  motor_get_min_positionResponse_()
    : position(0.0)  {
    }
  motor_get_min_positionResponse_(const ContainerAllocator& _alloc)
    : position(0.0)  {
    }



   typedef double _position_type;
  _position_type position;




  typedef boost::shared_ptr< ::nodes::motor_get_min_positionResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::nodes::motor_get_min_positionResponse_<ContainerAllocator> const> ConstPtr;

}; // struct motor_get_min_positionResponse_

typedef ::nodes::motor_get_min_positionResponse_<std::allocator<void> > motor_get_min_positionResponse;

typedef boost::shared_ptr< ::nodes::motor_get_min_positionResponse > motor_get_min_positionResponsePtr;
typedef boost::shared_ptr< ::nodes::motor_get_min_positionResponse const> motor_get_min_positionResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::nodes::motor_get_min_positionResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::nodes::motor_get_min_positionResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace nodes

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'nodes': ['/home/legged/tns_ros1/controllers/joystick/catkin_ws/src/nodes/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::nodes::motor_get_min_positionResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::nodes::motor_get_min_positionResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::nodes::motor_get_min_positionResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::nodes::motor_get_min_positionResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::nodes::motor_get_min_positionResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::nodes::motor_get_min_positionResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::nodes::motor_get_min_positionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "81d629500ad53a56e7ab2ad1949abc81";
  }

  static const char* value(const ::nodes::motor_get_min_positionResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x81d629500ad53a56ULL;
  static const uint64_t static_value2 = 0xe7ab2ad1949abc81ULL;
};

template<class ContainerAllocator>
struct DataType< ::nodes::motor_get_min_positionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "nodes/motor_get_min_positionResponse";
  }

  static const char* value(const ::nodes::motor_get_min_positionResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::nodes::motor_get_min_positionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 position\n\
\n\
";
  }

  static const char* value(const ::nodes::motor_get_min_positionResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::nodes::motor_get_min_positionResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.position);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct motor_get_min_positionResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::nodes::motor_get_min_positionResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::nodes::motor_get_min_positionResponse_<ContainerAllocator>& v)
  {
    s << indent << "position: ";
    Printer<double>::stream(s, indent + "  ", v.position);
  }
};

} // namespace message_operations
} // namespace ros

#endif // NODES_MESSAGE_MOTOR_GET_MIN_POSITIONRESPONSE_H
