// Generated by gencpp from file nodes/motor_get_target_position.msg
// DO NOT EDIT!


#ifndef NODES_MESSAGE_MOTOR_GET_TARGET_POSITION_H
#define NODES_MESSAGE_MOTOR_GET_TARGET_POSITION_H

#include <ros/service_traits.h>


#include <nodes/motor_get_target_positionRequest.h>
#include <nodes/motor_get_target_positionResponse.h>


namespace nodes
{

struct motor_get_target_position
{

typedef motor_get_target_positionRequest Request;
typedef motor_get_target_positionResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct motor_get_target_position
} // namespace nodes


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::nodes::motor_get_target_position > {
  static const char* value()
  {
    return "8dd818679eb62d4bbff36914669e9367";
  }

  static const char* value(const ::nodes::motor_get_target_position&) { return value(); }
};

template<>
struct DataType< ::nodes::motor_get_target_position > {
  static const char* value()
  {
    return "nodes/motor_get_target_position";
  }

  static const char* value(const ::nodes::motor_get_target_position&) { return value(); }
};


// service_traits::MD5Sum< ::nodes::motor_get_target_positionRequest> should match 
// service_traits::MD5Sum< ::nodes::motor_get_target_position > 
template<>
struct MD5Sum< ::nodes::motor_get_target_positionRequest>
{
  static const char* value()
  {
    return MD5Sum< ::nodes::motor_get_target_position >::value();
  }
  static const char* value(const ::nodes::motor_get_target_positionRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::nodes::motor_get_target_positionRequest> should match 
// service_traits::DataType< ::nodes::motor_get_target_position > 
template<>
struct DataType< ::nodes::motor_get_target_positionRequest>
{
  static const char* value()
  {
    return DataType< ::nodes::motor_get_target_position >::value();
  }
  static const char* value(const ::nodes::motor_get_target_positionRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::nodes::motor_get_target_positionResponse> should match 
// service_traits::MD5Sum< ::nodes::motor_get_target_position > 
template<>
struct MD5Sum< ::nodes::motor_get_target_positionResponse>
{
  static const char* value()
  {
    return MD5Sum< ::nodes::motor_get_target_position >::value();
  }
  static const char* value(const ::nodes::motor_get_target_positionResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::nodes::motor_get_target_positionResponse> should match 
// service_traits::DataType< ::nodes::motor_get_target_position > 
template<>
struct DataType< ::nodes::motor_get_target_positionResponse>
{
  static const char* value()
  {
    return DataType< ::nodes::motor_get_target_position >::value();
  }
  static const char* value(const ::nodes::motor_get_target_positionResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // NODES_MESSAGE_MOTOR_GET_TARGET_POSITION_H
