// Generated by gencpp from file nodes/motor_set_force.msg
// DO NOT EDIT!


#ifndef NODES_MESSAGE_MOTOR_SET_FORCE_H
#define NODES_MESSAGE_MOTOR_SET_FORCE_H

#include <ros/service_traits.h>


#include <nodes/motor_set_forceRequest.h>
#include <nodes/motor_set_forceResponse.h>


namespace nodes
{

struct motor_set_force
{

typedef motor_set_forceRequest Request;
typedef motor_set_forceResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct motor_set_force
} // namespace nodes


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::nodes::motor_set_force > {
  static const char* value()
  {
    return "9bdb99d1c404938fb4a979d48a5957a6";
  }

  static const char* value(const ::nodes::motor_set_force&) { return value(); }
};

template<>
struct DataType< ::nodes::motor_set_force > {
  static const char* value()
  {
    return "nodes/motor_set_force";
  }

  static const char* value(const ::nodes::motor_set_force&) { return value(); }
};


// service_traits::MD5Sum< ::nodes::motor_set_forceRequest> should match 
// service_traits::MD5Sum< ::nodes::motor_set_force > 
template<>
struct MD5Sum< ::nodes::motor_set_forceRequest>
{
  static const char* value()
  {
    return MD5Sum< ::nodes::motor_set_force >::value();
  }
  static const char* value(const ::nodes::motor_set_forceRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::nodes::motor_set_forceRequest> should match 
// service_traits::DataType< ::nodes::motor_set_force > 
template<>
struct DataType< ::nodes::motor_set_forceRequest>
{
  static const char* value()
  {
    return DataType< ::nodes::motor_set_force >::value();
  }
  static const char* value(const ::nodes::motor_set_forceRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::nodes::motor_set_forceResponse> should match 
// service_traits::MD5Sum< ::nodes::motor_set_force > 
template<>
struct MD5Sum< ::nodes::motor_set_forceResponse>
{
  static const char* value()
  {
    return MD5Sum< ::nodes::motor_set_force >::value();
  }
  static const char* value(const ::nodes::motor_set_forceResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::nodes::motor_set_forceResponse> should match 
// service_traits::DataType< ::nodes::motor_set_force > 
template<>
struct DataType< ::nodes::motor_set_forceResponse>
{
  static const char* value()
  {
    return DataType< ::nodes::motor_set_force >::value();
  }
  static const char* value(const ::nodes::motor_set_forceResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // NODES_MESSAGE_MOTOR_SET_FORCE_H
