// Generated by gencpp from file nodes/node_get_field.msg
// DO NOT EDIT!


#ifndef NODES_MESSAGE_NODE_GET_FIELD_H
#define NODES_MESSAGE_NODE_GET_FIELD_H

#include <ros/service_traits.h>


#include <nodes/node_get_fieldRequest.h>
#include <nodes/node_get_fieldResponse.h>


namespace nodes
{

struct node_get_field
{

typedef node_get_fieldRequest Request;
typedef node_get_fieldResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct node_get_field
} // namespace nodes


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::nodes::node_get_field > {
  static const char* value()
  {
    return "ebc69c91abb4723f5b25baca5ecfe051";
  }

  static const char* value(const ::nodes::node_get_field&) { return value(); }
};

template<>
struct DataType< ::nodes::node_get_field > {
  static const char* value()
  {
    return "nodes/node_get_field";
  }

  static const char* value(const ::nodes::node_get_field&) { return value(); }
};


// service_traits::MD5Sum< ::nodes::node_get_fieldRequest> should match 
// service_traits::MD5Sum< ::nodes::node_get_field > 
template<>
struct MD5Sum< ::nodes::node_get_fieldRequest>
{
  static const char* value()
  {
    return MD5Sum< ::nodes::node_get_field >::value();
  }
  static const char* value(const ::nodes::node_get_fieldRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::nodes::node_get_fieldRequest> should match 
// service_traits::DataType< ::nodes::node_get_field > 
template<>
struct DataType< ::nodes::node_get_fieldRequest>
{
  static const char* value()
  {
    return DataType< ::nodes::node_get_field >::value();
  }
  static const char* value(const ::nodes::node_get_fieldRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::nodes::node_get_fieldResponse> should match 
// service_traits::MD5Sum< ::nodes::node_get_field > 
template<>
struct MD5Sum< ::nodes::node_get_fieldResponse>
{
  static const char* value()
  {
    return MD5Sum< ::nodes::node_get_field >::value();
  }
  static const char* value(const ::nodes::node_get_fieldResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::nodes::node_get_fieldResponse> should match 
// service_traits::DataType< ::nodes::node_get_field > 
template<>
struct DataType< ::nodes::node_get_fieldResponse>
{
  static const char* value()
  {
    return DataType< ::nodes::node_get_field >::value();
  }
  static const char* value(const ::nodes::node_get_fieldResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // NODES_MESSAGE_NODE_GET_FIELD_H
