// Generated by gencpp from file nodes/pen_set_ink_colorRequest.msg
// DO NOT EDIT!


#ifndef NODES_MESSAGE_PEN_SET_INK_COLORREQUEST_H
#define NODES_MESSAGE_PEN_SET_INK_COLORREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace nodes
{
template <class ContainerAllocator>
struct pen_set_ink_colorRequest_
{
  typedef pen_set_ink_colorRequest_<ContainerAllocator> Type;

  pen_set_ink_colorRequest_()
    : color(0)
    , density(0.0)  {
    }
  pen_set_ink_colorRequest_(const ContainerAllocator& _alloc)
    : color(0)
    , density(0.0)  {
    }



   typedef int32_t _color_type;
  _color_type color;

   typedef double _density_type;
  _density_type density;




  typedef boost::shared_ptr< ::nodes::pen_set_ink_colorRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::nodes::pen_set_ink_colorRequest_<ContainerAllocator> const> ConstPtr;

}; // struct pen_set_ink_colorRequest_

typedef ::nodes::pen_set_ink_colorRequest_<std::allocator<void> > pen_set_ink_colorRequest;

typedef boost::shared_ptr< ::nodes::pen_set_ink_colorRequest > pen_set_ink_colorRequestPtr;
typedef boost::shared_ptr< ::nodes::pen_set_ink_colorRequest const> pen_set_ink_colorRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::nodes::pen_set_ink_colorRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::nodes::pen_set_ink_colorRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace nodes

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'nodes': ['/home/legged/tns_ros1/controllers/joystick/catkin_ws/src/nodes/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::nodes::pen_set_ink_colorRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::nodes::pen_set_ink_colorRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::nodes::pen_set_ink_colorRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::nodes::pen_set_ink_colorRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::nodes::pen_set_ink_colorRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::nodes::pen_set_ink_colorRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::nodes::pen_set_ink_colorRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "156d8b74482921c561726aaf09907de8";
  }

  static const char* value(const ::nodes::pen_set_ink_colorRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x156d8b74482921c5ULL;
  static const uint64_t static_value2 = 0x61726aaf09907de8ULL;
};

template<class ContainerAllocator>
struct DataType< ::nodes::pen_set_ink_colorRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "nodes/pen_set_ink_colorRequest";
  }

  static const char* value(const ::nodes::pen_set_ink_colorRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::nodes::pen_set_ink_colorRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 color\n\
float64 density\n\
";
  }

  static const char* value(const ::nodes::pen_set_ink_colorRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::nodes::pen_set_ink_colorRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.color);
      stream.next(m.density);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct pen_set_ink_colorRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::nodes::pen_set_ink_colorRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::nodes::pen_set_ink_colorRequest_<ContainerAllocator>& v)
  {
    s << indent << "color: ";
    Printer<int32_t>::stream(s, indent + "  ", v.color);
    s << indent << "density: ";
    Printer<double>::stream(s, indent + "  ", v.density);
  }
};

} // namespace message_operations
} // namespace ros

#endif // NODES_MESSAGE_PEN_SET_INK_COLORREQUEST_H
