// Generated by gencpp from file nodes/receiver_get_data_size.msg
// DO NOT EDIT!


#ifndef NODES_MESSAGE_RECEIVER_GET_DATA_SIZE_H
#define NODES_MESSAGE_RECEIVER_GET_DATA_SIZE_H

#include <ros/service_traits.h>


#include <nodes/receiver_get_data_sizeRequest.h>
#include <nodes/receiver_get_data_sizeResponse.h>


namespace nodes
{

struct receiver_get_data_size
{

typedef receiver_get_data_sizeRequest Request;
typedef receiver_get_data_sizeResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct receiver_get_data_size
} // namespace nodes


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::nodes::receiver_get_data_size > {
  static const char* value()
  {
    return "27a11ce8d1e9e8846f091b6b5f11f310";
  }

  static const char* value(const ::nodes::receiver_get_data_size&) { return value(); }
};

template<>
struct DataType< ::nodes::receiver_get_data_size > {
  static const char* value()
  {
    return "nodes/receiver_get_data_size";
  }

  static const char* value(const ::nodes::receiver_get_data_size&) { return value(); }
};


// service_traits::MD5Sum< ::nodes::receiver_get_data_sizeRequest> should match 
// service_traits::MD5Sum< ::nodes::receiver_get_data_size > 
template<>
struct MD5Sum< ::nodes::receiver_get_data_sizeRequest>
{
  static const char* value()
  {
    return MD5Sum< ::nodes::receiver_get_data_size >::value();
  }
  static const char* value(const ::nodes::receiver_get_data_sizeRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::nodes::receiver_get_data_sizeRequest> should match 
// service_traits::DataType< ::nodes::receiver_get_data_size > 
template<>
struct DataType< ::nodes::receiver_get_data_sizeRequest>
{
  static const char* value()
  {
    return DataType< ::nodes::receiver_get_data_size >::value();
  }
  static const char* value(const ::nodes::receiver_get_data_sizeRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::nodes::receiver_get_data_sizeResponse> should match 
// service_traits::MD5Sum< ::nodes::receiver_get_data_size > 
template<>
struct MD5Sum< ::nodes::receiver_get_data_sizeResponse>
{
  static const char* value()
  {
    return MD5Sum< ::nodes::receiver_get_data_size >::value();
  }
  static const char* value(const ::nodes::receiver_get_data_sizeResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::nodes::receiver_get_data_sizeResponse> should match 
// service_traits::DataType< ::nodes::receiver_get_data_size > 
template<>
struct DataType< ::nodes::receiver_get_data_sizeResponse>
{
  static const char* value()
  {
    return DataType< ::nodes::receiver_get_data_size >::value();
  }
  static const char* value(const ::nodes::receiver_get_data_sizeResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // NODES_MESSAGE_RECEIVER_GET_DATA_SIZE_H
