// Generated by gencpp from file nodes/receiver_get_data_sizeResponse.msg
// DO NOT EDIT!


#ifndef NODES_MESSAGE_RECEIVER_GET_DATA_SIZERESPONSE_H
#define NODES_MESSAGE_RECEIVER_GET_DATA_SIZERESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace nodes
{
template <class ContainerAllocator>
struct receiver_get_data_sizeResponse_
{
  typedef receiver_get_data_sizeResponse_<ContainerAllocator> Type;

  receiver_get_data_sizeResponse_()
    : size(0)  {
    }
  receiver_get_data_sizeResponse_(const ContainerAllocator& _alloc)
    : size(0)  {
    }



   typedef int32_t _size_type;
  _size_type size;




  typedef boost::shared_ptr< ::nodes::receiver_get_data_sizeResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::nodes::receiver_get_data_sizeResponse_<ContainerAllocator> const> ConstPtr;

}; // struct receiver_get_data_sizeResponse_

typedef ::nodes::receiver_get_data_sizeResponse_<std::allocator<void> > receiver_get_data_sizeResponse;

typedef boost::shared_ptr< ::nodes::receiver_get_data_sizeResponse > receiver_get_data_sizeResponsePtr;
typedef boost::shared_ptr< ::nodes::receiver_get_data_sizeResponse const> receiver_get_data_sizeResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::nodes::receiver_get_data_sizeResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::nodes::receiver_get_data_sizeResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace nodes

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'nodes': ['/home/legged/tns_ros1/controllers/joystick/catkin_ws/src/nodes/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::nodes::receiver_get_data_sizeResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::nodes::receiver_get_data_sizeResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::nodes::receiver_get_data_sizeResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::nodes::receiver_get_data_sizeResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::nodes::receiver_get_data_sizeResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::nodes::receiver_get_data_sizeResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::nodes::receiver_get_data_sizeResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "97da5de9999c5ce84f539773c8d0b2a3";
  }

  static const char* value(const ::nodes::receiver_get_data_sizeResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x97da5de9999c5ce8ULL;
  static const uint64_t static_value2 = 0x4f539773c8d0b2a3ULL;
};

template<class ContainerAllocator>
struct DataType< ::nodes::receiver_get_data_sizeResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "nodes/receiver_get_data_sizeResponse";
  }

  static const char* value(const ::nodes::receiver_get_data_sizeResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::nodes::receiver_get_data_sizeResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 size\n\
\n\
";
  }

  static const char* value(const ::nodes::receiver_get_data_sizeResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::nodes::receiver_get_data_sizeResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.size);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct receiver_get_data_sizeResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::nodes::receiver_get_data_sizeResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::nodes::receiver_get_data_sizeResponse_<ContainerAllocator>& v)
  {
    s << indent << "size: ";
    Printer<int32_t>::stream(s, indent + "  ", v.size);
  }
};

} // namespace message_operations
} // namespace ros

#endif // NODES_MESSAGE_RECEIVER_GET_DATA_SIZERESPONSE_H
