// Generated by gencpp from file nodes/robot_set_time_step.msg
// DO NOT EDIT!


#ifndef NODES_MESSAGE_ROBOT_SET_TIME_STEP_H
#define NODES_MESSAGE_ROBOT_SET_TIME_STEP_H

#include <ros/service_traits.h>


#include <nodes/robot_set_time_stepRequest.h>
#include <nodes/robot_set_time_stepResponse.h>


namespace nodes
{

struct robot_set_time_step
{

typedef robot_set_time_stepRequest Request;
typedef robot_set_time_stepResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct robot_set_time_step
} // namespace nodes


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::nodes::robot_set_time_step > {
  static const char* value()
  {
    return "73b2cdfee76569e764e930eff0a564a5";
  }

  static const char* value(const ::nodes::robot_set_time_step&) { return value(); }
};

template<>
struct DataType< ::nodes::robot_set_time_step > {
  static const char* value()
  {
    return "nodes/robot_set_time_step";
  }

  static const char* value(const ::nodes::robot_set_time_step&) { return value(); }
};


// service_traits::MD5Sum< ::nodes::robot_set_time_stepRequest> should match 
// service_traits::MD5Sum< ::nodes::robot_set_time_step > 
template<>
struct MD5Sum< ::nodes::robot_set_time_stepRequest>
{
  static const char* value()
  {
    return MD5Sum< ::nodes::robot_set_time_step >::value();
  }
  static const char* value(const ::nodes::robot_set_time_stepRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::nodes::robot_set_time_stepRequest> should match 
// service_traits::DataType< ::nodes::robot_set_time_step > 
template<>
struct DataType< ::nodes::robot_set_time_stepRequest>
{
  static const char* value()
  {
    return DataType< ::nodes::robot_set_time_step >::value();
  }
  static const char* value(const ::nodes::robot_set_time_stepRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::nodes::robot_set_time_stepResponse> should match 
// service_traits::MD5Sum< ::nodes::robot_set_time_step > 
template<>
struct MD5Sum< ::nodes::robot_set_time_stepResponse>
{
  static const char* value()
  {
    return MD5Sum< ::nodes::robot_set_time_step >::value();
  }
  static const char* value(const ::nodes::robot_set_time_stepResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::nodes::robot_set_time_stepResponse> should match 
// service_traits::DataType< ::nodes::robot_set_time_step > 
template<>
struct DataType< ::nodes::robot_set_time_stepResponse>
{
  static const char* value()
  {
    return DataType< ::nodes::robot_set_time_step >::value();
  }
  static const char* value(const ::nodes::robot_set_time_stepResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // NODES_MESSAGE_ROBOT_SET_TIME_STEP_H
