// Generated by gencpp from file nodes/robot_device_listResponse.msg
// DO NOT EDIT!


#ifndef NODES_MESSAGE_ROBOT_DEVICE_LISTRESPONSE_H
#define NODES_MESSAGE_ROBOT_DEVICE_LISTRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace nodes
{
template <class ContainerAllocator>
struct robot_device_listResponse_
{
  typedef robot_device_listResponse_<ContainerAllocator> Type;

  robot_device_listResponse_()
    : list()  {
    }
  robot_device_listResponse_(const ContainerAllocator& _alloc)
    : list(_alloc)  {
    }



   typedef std::vector<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > , typename ContainerAllocator::template rebind<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::other >  _list_type;
  _list_type list;




  typedef boost::shared_ptr< ::nodes::robot_device_listResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::nodes::robot_device_listResponse_<ContainerAllocator> const> ConstPtr;

}; // struct robot_device_listResponse_

typedef ::nodes::robot_device_listResponse_<std::allocator<void> > robot_device_listResponse;

typedef boost::shared_ptr< ::nodes::robot_device_listResponse > robot_device_listResponsePtr;
typedef boost::shared_ptr< ::nodes::robot_device_listResponse const> robot_device_listResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::nodes::robot_device_listResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::nodes::robot_device_listResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace nodes

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'nodes': ['/home/legged/tns_ros1/controllers/joystick/catkin_ws/src/nodes/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::nodes::robot_device_listResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::nodes::robot_device_listResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::nodes::robot_device_listResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::nodes::robot_device_listResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::nodes::robot_device_listResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::nodes::robot_device_listResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::nodes::robot_device_listResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8e09fa9aad51508cfdcab3b64f048ce0";
  }

  static const char* value(const ::nodes::robot_device_listResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8e09fa9aad51508cULL;
  static const uint64_t static_value2 = 0xfdcab3b64f048ce0ULL;
};

template<class ContainerAllocator>
struct DataType< ::nodes::robot_device_listResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "nodes/robot_device_listResponse";
  }

  static const char* value(const ::nodes::robot_device_listResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::nodes::robot_device_listResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string[] list\n\
\n\
";
  }

  static const char* value(const ::nodes::robot_device_listResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::nodes::robot_device_listResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.list);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct robot_device_listResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::nodes::robot_device_listResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::nodes::robot_device_listResponse_<ContainerAllocator>& v)
  {
    s << indent << "list[]" << std::endl;
    for (size_t i = 0; i < v.list.size(); ++i)
    {
      s << indent << "  list[" << i << "]: ";
      Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.list[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // NODES_MESSAGE_ROBOT_DEVICE_LISTRESPONSE_H
