// Generated by gencpp from file nodes/robot_get_project_pathResponse.msg
// DO NOT EDIT!


#ifndef NODES_MESSAGE_ROBOT_GET_PROJECT_PATHRESPONSE_H
#define NODES_MESSAGE_ROBOT_GET_PROJECT_PATHRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace nodes
{
template <class ContainerAllocator>
struct robot_get_project_pathResponse_
{
  typedef robot_get_project_pathResponse_<ContainerAllocator> Type;

  robot_get_project_pathResponse_()
    : path()  {
    }
  robot_get_project_pathResponse_(const ContainerAllocator& _alloc)
    : path(_alloc)  {
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _path_type;
  _path_type path;




  typedef boost::shared_ptr< ::nodes::robot_get_project_pathResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::nodes::robot_get_project_pathResponse_<ContainerAllocator> const> ConstPtr;

}; // struct robot_get_project_pathResponse_

typedef ::nodes::robot_get_project_pathResponse_<std::allocator<void> > robot_get_project_pathResponse;

typedef boost::shared_ptr< ::nodes::robot_get_project_pathResponse > robot_get_project_pathResponsePtr;
typedef boost::shared_ptr< ::nodes::robot_get_project_pathResponse const> robot_get_project_pathResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::nodes::robot_get_project_pathResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::nodes::robot_get_project_pathResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace nodes

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'nodes': ['/home/legged/tns_ros1/controllers/joystick/catkin_ws/src/nodes/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::nodes::robot_get_project_pathResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::nodes::robot_get_project_pathResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::nodes::robot_get_project_pathResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::nodes::robot_get_project_pathResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::nodes::robot_get_project_pathResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::nodes::robot_get_project_pathResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::nodes::robot_get_project_pathResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1d00cd540af97efeb6b1589112fab63e";
  }

  static const char* value(const ::nodes::robot_get_project_pathResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1d00cd540af97efeULL;
  static const uint64_t static_value2 = 0xb6b1589112fab63eULL;
};

template<class ContainerAllocator>
struct DataType< ::nodes::robot_get_project_pathResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "nodes/robot_get_project_pathResponse";
  }

  static const char* value(const ::nodes::robot_get_project_pathResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::nodes::robot_get_project_pathResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string path\n\
\n\
";
  }

  static const char* value(const ::nodes::robot_get_project_pathResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::nodes::robot_get_project_pathResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.path);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct robot_get_project_pathResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::nodes::robot_get_project_pathResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::nodes::robot_get_project_pathResponse_<ContainerAllocator>& v)
  {
    s << indent << "path: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.path);
  }
};

} // namespace message_operations
} // namespace ros

#endif // NODES_MESSAGE_ROBOT_GET_PROJECT_PATHRESPONSE_H
