// Generated by gencpp from file nodes/robot_get_project_path.msg
// DO NOT EDIT!


#ifndef NODES_MESSAGE_ROBOT_GET_PROJECT_PATH_H
#define NODES_MESSAGE_ROBOT_GET_PROJECT_PATH_H

#include <ros/service_traits.h>


#include <nodes/robot_get_project_pathRequest.h>
#include <nodes/robot_get_project_pathResponse.h>


namespace nodes
{

struct robot_get_project_path
{

typedef robot_get_project_pathRequest Request;
typedef robot_get_project_pathResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct robot_get_project_path
} // namespace nodes


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::nodes::robot_get_project_path > {
  static const char* value()
  {
    return "fe494ce3859bc7201e535d02fca42e4e";
  }

  static const char* value(const ::nodes::robot_get_project_path&) { return value(); }
};

template<>
struct DataType< ::nodes::robot_get_project_path > {
  static const char* value()
  {
    return "nodes/robot_get_project_path";
  }

  static const char* value(const ::nodes::robot_get_project_path&) { return value(); }
};


// service_traits::MD5Sum< ::nodes::robot_get_project_pathRequest> should match 
// service_traits::MD5Sum< ::nodes::robot_get_project_path > 
template<>
struct MD5Sum< ::nodes::robot_get_project_pathRequest>
{
  static const char* value()
  {
    return MD5Sum< ::nodes::robot_get_project_path >::value();
  }
  static const char* value(const ::nodes::robot_get_project_pathRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::nodes::robot_get_project_pathRequest> should match 
// service_traits::DataType< ::nodes::robot_get_project_path > 
template<>
struct DataType< ::nodes::robot_get_project_pathRequest>
{
  static const char* value()
  {
    return DataType< ::nodes::robot_get_project_path >::value();
  }
  static const char* value(const ::nodes::robot_get_project_pathRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::nodes::robot_get_project_pathResponse> should match 
// service_traits::MD5Sum< ::nodes::robot_get_project_path > 
template<>
struct MD5Sum< ::nodes::robot_get_project_pathResponse>
{
  static const char* value()
  {
    return MD5Sum< ::nodes::robot_get_project_path >::value();
  }
  static const char* value(const ::nodes::robot_get_project_pathResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::nodes::robot_get_project_pathResponse> should match 
// service_traits::DataType< ::nodes::robot_get_project_path > 
template<>
struct DataType< ::nodes::robot_get_project_pathResponse>
{
  static const char* value()
  {
    return DataType< ::nodes::robot_get_project_path >::value();
  }
  static const char* value(const ::nodes::robot_get_project_pathResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // NODES_MESSAGE_ROBOT_GET_PROJECT_PATH_H
