// Generated by gencpp from file nodes/robot_set_mode.msg
// DO NOT EDIT!


#ifndef NODES_MESSAGE_ROBOT_SET_MODE_H
#define NODES_MESSAGE_ROBOT_SET_MODE_H

#include <ros/service_traits.h>


#include <nodes/robot_set_modeRequest.h>
#include <nodes/robot_set_modeResponse.h>


namespace nodes
{

struct robot_set_mode
{

typedef robot_set_modeRequest Request;
typedef robot_set_modeResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct robot_set_mode
} // namespace nodes


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::nodes::robot_set_mode > {
  static const char* value()
  {
    return "ef8b4f277f1a6d92a8c4d6a68a3850de";
  }

  static const char* value(const ::nodes::robot_set_mode&) { return value(); }
};

template<>
struct DataType< ::nodes::robot_set_mode > {
  static const char* value()
  {
    return "nodes/robot_set_mode";
  }

  static const char* value(const ::nodes::robot_set_mode&) { return value(); }
};


// service_traits::MD5Sum< ::nodes::robot_set_modeRequest> should match 
// service_traits::MD5Sum< ::nodes::robot_set_mode > 
template<>
struct MD5Sum< ::nodes::robot_set_modeRequest>
{
  static const char* value()
  {
    return MD5Sum< ::nodes::robot_set_mode >::value();
  }
  static const char* value(const ::nodes::robot_set_modeRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::nodes::robot_set_modeRequest> should match 
// service_traits::DataType< ::nodes::robot_set_mode > 
template<>
struct DataType< ::nodes::robot_set_modeRequest>
{
  static const char* value()
  {
    return DataType< ::nodes::robot_set_mode >::value();
  }
  static const char* value(const ::nodes::robot_set_modeRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::nodes::robot_set_modeResponse> should match 
// service_traits::MD5Sum< ::nodes::robot_set_mode > 
template<>
struct MD5Sum< ::nodes::robot_set_modeResponse>
{
  static const char* value()
  {
    return MD5Sum< ::nodes::robot_set_mode >::value();
  }
  static const char* value(const ::nodes::robot_set_modeResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::nodes::robot_set_modeResponse> should match 
// service_traits::DataType< ::nodes::robot_set_mode > 
template<>
struct DataType< ::nodes::robot_set_modeResponse>
{
  static const char* value()
  {
    return DataType< ::nodes::robot_set_mode >::value();
  }
  static const char* value(const ::nodes::robot_set_modeResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // NODES_MESSAGE_ROBOT_SET_MODE_H
