// Generated by gencpp from file nodes/sensor_sampling_period.msg
// DO NOT EDIT!


#ifndef NODES_MESSAGE_SENSOR_SAMPLING_PERIOD_H
#define NODES_MESSAGE_SENSOR_SAMPLING_PERIOD_H

#include <ros/service_traits.h>


#include <nodes/sensor_sampling_periodRequest.h>
#include <nodes/sensor_sampling_periodResponse.h>


namespace nodes
{

struct sensor_sampling_period
{

typedef sensor_sampling_periodRequest Request;
typedef sensor_sampling_periodResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct sensor_sampling_period
} // namespace nodes


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::nodes::sensor_sampling_period > {
  static const char* value()
  {
    return "b63e210df66cfd7c87450de452ecf773";
  }

  static const char* value(const ::nodes::sensor_sampling_period&) { return value(); }
};

template<>
struct DataType< ::nodes::sensor_sampling_period > {
  static const char* value()
  {
    return "nodes/sensor_sampling_period";
  }

  static const char* value(const ::nodes::sensor_sampling_period&) { return value(); }
};


// service_traits::MD5Sum< ::nodes::sensor_sampling_periodRequest> should match 
// service_traits::MD5Sum< ::nodes::sensor_sampling_period > 
template<>
struct MD5Sum< ::nodes::sensor_sampling_periodRequest>
{
  static const char* value()
  {
    return MD5Sum< ::nodes::sensor_sampling_period >::value();
  }
  static const char* value(const ::nodes::sensor_sampling_periodRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::nodes::sensor_sampling_periodRequest> should match 
// service_traits::DataType< ::nodes::sensor_sampling_period > 
template<>
struct DataType< ::nodes::sensor_sampling_periodRequest>
{
  static const char* value()
  {
    return DataType< ::nodes::sensor_sampling_period >::value();
  }
  static const char* value(const ::nodes::sensor_sampling_periodRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::nodes::sensor_sampling_periodResponse> should match 
// service_traits::MD5Sum< ::nodes::sensor_sampling_period > 
template<>
struct MD5Sum< ::nodes::sensor_sampling_periodResponse>
{
  static const char* value()
  {
    return MD5Sum< ::nodes::sensor_sampling_period >::value();
  }
  static const char* value(const ::nodes::sensor_sampling_periodResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::nodes::sensor_sampling_periodResponse> should match 
// service_traits::DataType< ::nodes::sensor_sampling_period > 
template<>
struct DataType< ::nodes::sensor_sampling_periodResponse>
{
  static const char* value()
  {
    return DataType< ::nodes::sensor_sampling_period >::value();
  }
  static const char* value(const ::nodes::sensor_sampling_periodResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // NODES_MESSAGE_SENSOR_SAMPLING_PERIOD_H
