// Generated by gencpp from file nodes/supervisor_start_movie.msg
// DO NOT EDIT!


#ifndef NODES_MESSAGE_SUPERVISOR_START_MOVIE_H
#define NODES_MESSAGE_SUPERVISOR_START_MOVIE_H

#include <ros/service_traits.h>


#include <nodes/supervisor_start_movieRequest.h>
#include <nodes/supervisor_start_movieResponse.h>


namespace nodes
{

struct supervisor_start_movie
{

typedef supervisor_start_movieRequest Request;
typedef supervisor_start_movieResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct supervisor_start_movie
} // namespace nodes


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::nodes::supervisor_start_movie > {
  static const char* value()
  {
    return "96ca298eece1e7a6fe756c404839bdcc";
  }

  static const char* value(const ::nodes::supervisor_start_movie&) { return value(); }
};

template<>
struct DataType< ::nodes::supervisor_start_movie > {
  static const char* value()
  {
    return "nodes/supervisor_start_movie";
  }

  static const char* value(const ::nodes::supervisor_start_movie&) { return value(); }
};


// service_traits::MD5Sum< ::nodes::supervisor_start_movieRequest> should match 
// service_traits::MD5Sum< ::nodes::supervisor_start_movie > 
template<>
struct MD5Sum< ::nodes::supervisor_start_movieRequest>
{
  static const char* value()
  {
    return MD5Sum< ::nodes::supervisor_start_movie >::value();
  }
  static const char* value(const ::nodes::supervisor_start_movieRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::nodes::supervisor_start_movieRequest> should match 
// service_traits::DataType< ::nodes::supervisor_start_movie > 
template<>
struct DataType< ::nodes::supervisor_start_movieRequest>
{
  static const char* value()
  {
    return DataType< ::nodes::supervisor_start_movie >::value();
  }
  static const char* value(const ::nodes::supervisor_start_movieRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::nodes::supervisor_start_movieResponse> should match 
// service_traits::MD5Sum< ::nodes::supervisor_start_movie > 
template<>
struct MD5Sum< ::nodes::supervisor_start_movieResponse>
{
  static const char* value()
  {
    return MD5Sum< ::nodes::supervisor_start_movie >::value();
  }
  static const char* value(const ::nodes::supervisor_start_movieResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::nodes::supervisor_start_movieResponse> should match 
// service_traits::DataType< ::nodes::supervisor_start_movie > 
template<>
struct DataType< ::nodes::supervisor_start_movieResponse>
{
  static const char* value()
  {
    return DataType< ::nodes::supervisor_start_movie >::value();
  }
  static const char* value(const ::nodes::supervisor_start_movieResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // NODES_MESSAGE_SUPERVISOR_START_MOVIE_H
