// Generated by gencpp from file nodes/supervisor_stop_movie.msg
// DO NOT EDIT!


#ifndef NODES_MESSAGE_SUPERVISOR_STOP_MOVIE_H
#define NODES_MESSAGE_SUPERVISOR_STOP_MOVIE_H

#include <ros/service_traits.h>


#include <nodes/supervisor_stop_movieRequest.h>
#include <nodes/supervisor_stop_movieResponse.h>


namespace nodes
{

struct supervisor_stop_movie
{

typedef supervisor_stop_movieRequest Request;
typedef supervisor_stop_movieResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct supervisor_stop_movie
} // namespace nodes


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::nodes::supervisor_stop_movie > {
  static const char* value()
  {
    return "2a42f8e83a0d1e81ff806bb0cbf4e594";
  }

  static const char* value(const ::nodes::supervisor_stop_movie&) { return value(); }
};

template<>
struct DataType< ::nodes::supervisor_stop_movie > {
  static const char* value()
  {
    return "nodes/supervisor_stop_movie";
  }

  static const char* value(const ::nodes::supervisor_stop_movie&) { return value(); }
};


// service_traits::MD5Sum< ::nodes::supervisor_stop_movieRequest> should match 
// service_traits::MD5Sum< ::nodes::supervisor_stop_movie > 
template<>
struct MD5Sum< ::nodes::supervisor_stop_movieRequest>
{
  static const char* value()
  {
    return MD5Sum< ::nodes::supervisor_stop_movie >::value();
  }
  static const char* value(const ::nodes::supervisor_stop_movieRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::nodes::supervisor_stop_movieRequest> should match 
// service_traits::DataType< ::nodes::supervisor_stop_movie > 
template<>
struct DataType< ::nodes::supervisor_stop_movieRequest>
{
  static const char* value()
  {
    return DataType< ::nodes::supervisor_stop_movie >::value();
  }
  static const char* value(const ::nodes::supervisor_stop_movieRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::nodes::supervisor_stop_movieResponse> should match 
// service_traits::MD5Sum< ::nodes::supervisor_stop_movie > 
template<>
struct MD5Sum< ::nodes::supervisor_stop_movieResponse>
{
  static const char* value()
  {
    return MD5Sum< ::nodes::supervisor_stop_movie >::value();
  }
  static const char* value(const ::nodes::supervisor_stop_movieResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::nodes::supervisor_stop_movieResponse> should match 
// service_traits::DataType< ::nodes::supervisor_stop_movie > 
template<>
struct DataType< ::nodes::supervisor_stop_movieResponse>
{
  static const char* value()
  {
    return DataType< ::nodes::supervisor_stop_movie >::value();
  }
  static const char* value(const ::nodes::supervisor_stop_movieResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // NODES_MESSAGE_SUPERVISOR_STOP_MOVIE_H
